### 학습목표
 - random 서브모듈 함수를 통해 ndarray 생성하기

In [1]:
import numpy as np

#### random 서브모듈

#### rand 함수
 - 0, 1사이의 분포로 랜덤한 ndarray 생성

In [2]:
np.random.rand(2, 3)

array([[0.88609522, 0.68307571, 0.46589935],
       [0.99737028, 0.07592654, 0.22318614]])

In [3]:
np.random.rand(10)

array([0.18977785, 0.34678323, 0.48902416, 0.48665138, 0.14350517,
       0.52336567, 0.56301895, 0.37406117, 0.39070684, 0.23654155])

In [4]:
np.random.rand(4, 5, 3)

array([[[0.67919817, 0.48373354, 0.09965567],
        [0.32648956, 0.40930565, 0.08764063],
        [0.2791597 , 0.22340208, 0.52804412],
        [0.01154512, 0.58838346, 0.24186949],
        [0.93202615, 0.2787187 , 0.482996  ]],

       [[0.02321079, 0.10637222, 0.25824866],
        [0.02088096, 0.66812079, 0.04524696],
        [0.39630781, 0.20911514, 0.19372856],
        [0.60463846, 0.43339337, 0.05737487],
        [0.6210773 , 0.20460235, 0.41491033]],

       [[0.60244061, 0.64388494, 0.41392867],
        [0.92119124, 0.60980919, 0.58351123],
        [0.804645  , 0.5542059 , 0.38430556],
        [0.4486338 , 0.98826392, 0.05309767],
        [0.34592464, 0.31837445, 0.20556943]],

       [[0.94288331, 0.73137755, 0.51666122],
        [0.6175703 , 0.26303911, 0.61376428],
        [0.88334812, 0.68038759, 0.60085058],
        [0.84284199, 0.15416167, 0.18106171],
        [0.12528023, 0.25577251, 0.02772738]]])

#### randn함수
 - n: normal distribution(정규분포)
 - 정규분포로 샘플링된 랜덤 ndarray 생성

In [5]:
np.random.randn(3, 4, 2)

array([[[ 0.58327308, -0.35498051],
        [ 0.11968371, -0.28512127],
        [-0.77284829,  1.19949088],
        [ 0.98579237, -0.57420551]],

       [[-0.43735631,  0.56585349],
        [ 0.54206293, -1.25980967],
        [ 0.88936586,  0.22350807],
        [ 1.24005522, -1.86865941]],

       [[-1.15112261,  0.44064948],
        [-0.61687397, -1.63577087],
        [ 1.22762247,  0.15287412],
        [-0.33073287, -0.37426446]]])

In [6]:
np.random.randn(5)

array([ 1.16870477,  0.61473908, -0.79164246, -0.36155013,  1.04168145])

#### randint 함수
 - 특정 정수 사이에서 랜덤하게 샘플링

In [7]:
np.random.randint(1, 100, size = (3, 5))

array([[98, 17, 87, 91, 91],
       [74,  3, 65, 92, 22],
       [32, 99, 26, 83, 54]])

In [8]:
np.random.randint(1, 100, size = (3, 5, 2))

array([[[ 7,  6],
        [89, 31],
        [30, 32],
        [96, 46],
        [71, 72]],

       [[46, 15],
        [83, 15],
        [10, 61],
        [32, 11],
        [62, 44]],

       [[29, 21],
        [14, 18],
        [16, 51],
        [15, 89],
        [28, 73]]])

#### seed 함수
 - 랜덤한 값을 동일하게 다시 생성하고자 할때 사용

In [9]:
np.random.seed(100)

In [11]:
np.random.randn(3, 4)

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
       [-0.18949583,  0.25500144, -0.45802699,  0.43516349]])

In [14]:
np.random.seed(100)
np.random.randn(3, 4)

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
       [-0.18949583,  0.25500144, -0.45802699,  0.43516349]])

#### choice
 - 주어진 1차원 ndarray로 부터 랜덤으로 샘플링
 - 정수가 주어진 경우, np.arange(해당숫자)로 간주

In [15]:
np.random.choice(100, (3, 4))

array([[83,  4, 91, 59],
       [67,  7, 49, 47],
       [65, 61, 14, 55]])

In [16]:
x = np.array([1, 2, 3, 1.5, 2.6, 4.9])
np.random.choice(x, size = (2, 2))

array([[1.5, 1. ],
       [3. , 2. ]])

#### 확률분포에 따른 ndarray 생성
 - uniform
 - normal 등등

In [17]:
np.random.uniform(1.0, 3.0, size = (4, 5))

array([[2.29338294, 1.28413075, 2.16277792, 1.95837987, 1.77283822],
       [1.88092989, 1.80951466, 1.88450807, 1.06024656, 2.55201063],
       [2.10191676, 1.76214681, 2.05853156, 2.9137538 , 1.35164262],
       [1.23660567, 2.72589134, 1.14973376, 2.65018972, 2.67226363]])

In [19]:
np.random.normal(size = (3, 4))
np.random.randn(3, 4)

array([[ 0.38405784, -0.0490925 , -1.60169118, -0.13876257],
       [ 0.01208627, -1.29814417, -0.12888604, -0.28292163],
       [-0.17916825,  0.67575177,  2.38059534, -1.14670086]])