### 학습목표
 - 다양한 방법으로 ndarray 생성하기

In [1]:
import numpy as np

#### np.array 함수로 생성하기

In [4]:
x = np.array([1, 2, 3, 4])
print(x)

y = np.array([[2, 3, 4], [1, 2, 5]])
print(y)

type(y)

[1 2 3 4]
[[2 3 4]
 [1 2 5]]


numpy.ndarray

#### np.arange 함수로 생성하기

In [6]:
#파이썬 range 함수와 동일
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#1부터 10까지 중 홀수만 출력
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [9]:
#5부터 100까지 중 5의 배수만 출력
np.arange(5, 101, 5)

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

#### np.ones, np.zeros로 생성하기

In [11]:
#4행 5열의 모든 원소가 1인 행렬
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
#3행 4열의 모든 원소가 1인 행렬 2개 출력
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [15]:
#3행 8열의 모든 원소가 0인 행렬 2개 출력
np.zeros((2, 3, 8))

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]])

#### np.empty, np.full로 생성하기

In [16]:
np.empty((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
#7로만 이루어진 3행 4열
np.full((3, 4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### np.eye로 생성하기
 - 단위 행렬 생성

In [19]:
#단위행렬() : 대각원소가 모두 1인 대각행렬
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### np.linspace로 생성하기

In [20]:
#1 ~ 10인 전체의 범위를 3개로 나누어라
np.linspace(1, 10, 3)

array([ 1. ,  5.5, 10. ])

In [21]:
#1 ~ 10인 전체의 범위를 4개로 나누어라
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

#### reshape 함수 활용
 - ndarray의 형태, 차원을 바꾸기 위해 사용

In [26]:
x = np.arange(1, 16)
print(x)

#1차원 
x.shape

#2차원 행렬
x.reshape(3, 5)

#3차원 행렬
x.reshape(5, 3, 1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])