## 학습목표
 1. linalg 서브모듈 함수 활용여 선형대수 연산하기

In [1]:
import numpy as np

#### np.linalg.inv
 - 역행렬을 구할 때 사용
 - 모든 차원의 값이 같아야 함

In [2]:
x = np.random.rand(3, 3)
print(x)

# 행렬의 곱 : @
x @ np.linalg.inv(x)

[[0.68125937 0.42191592 0.08683899]
 [0.71023453 0.70676813 0.12362578]
 [0.85059269 0.04179032 0.34481381]]


array([[ 1.00000000e+00,  2.22044605e-16,  5.55111512e-17],
       [-2.22044605e-16,  1.00000000e+00,  1.11022302e-16],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

#### np.linalg.solve
 - Ax = B 형태의 선형대수식 솔루션을 제공
 - 예제) 호랑이와 홍합의 합 : 25 호랑이 다리와 홍합 다리의 합은 64
   - x + y = 25
   - 2x + 4y = 64
   
 $$\begin{pmatrix} 1 & 1 \\ 2 & 4 \end{pmatrix}\begin{pmatrix} x \\ y \end{pmatrix}= \begin{pmatrix} 25 \\ 64 \end{pmatrix}$$


In [ ]:
A = np.array([[1, 1], [2, 4]])
B = np.array([25, 64])

x