## 학습목표
 1. linalg 서브모듈 함수 활용여 선형대수 연산하기

In [2]:
import numpy as np

#### np.linalg.inv
 - 역행렬을 구할 때 사용
 - 모든 차원의 값이 같아야 함

In [3]:
x = np.random.rand(3, 3)
print(x)

# 행렬의 곱 : @
x @ np.linalg.inv(x)

[[0.29307337 0.45795139 0.56457842]
 [0.2124584  0.43231857 0.85578978]
 [0.19136092 0.8259411  0.59221088]]


array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [-2.22044605e-16, -2.22044605e-16,  1.00000000e+00]])

#### np.linalg.solve
 - Ax = B 형태의 선형대수식 솔루션을 제공
 - 예제) 호랑이와 홍합의 합 : 25 호랑이 다리와 홍합 다리의 합은 64
   - x + y = 25
   - 2x + 4y = 64
   
 $$\begin{pmatrix} 1 & 1 \\ 2 & 4 \end{pmatrix}\begin{pmatrix} x \\ y \end{pmatrix}= \begin{pmatrix} 25 \\ 64 \end{pmatrix}$$


In [5]:
A = np.array([[1, 1], [2, 4]])
B = np.array([25, 64])

x = np.linalg.solve(A, B)
print(x)

[18.  7.]


In [6]:
np.allclose(A @ x, B)

True