## 학습목표
 1. numpy에서 자주 사용되는 함수들을 사용해보기

In [3]:
import numpy as np

#### numpy documentation
 - [numpy 공식 문서 링크](https://www.numpy.org/devdocs/reference/)
 - numpy에서 제공되는 함수등에 대한 문서

In [4]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.69943013 0.09725632 0.84329566 0.20485529 0.03590037]
 [0.22728322 0.80078536 0.37703024 0.43921384 0.80317776]
 [0.94100541 0.4461834  0.58704351 0.78758119 0.06443504]]


#### 연산 함수
 - add, substract, multiply, divide

In [6]:
np.add(x, y)   # 같은 위치의 원소들끼리 더해짐(단, shape이 같아야함)

array([[ 0.69943013,  1.09725632,  2.84329566,  3.20485529,  4.03590037],
       [ 5.22728322,  6.80078536,  7.37703024,  8.43921384,  9.80317776],
       [10.94100541, 11.4461834 , 12.58704351, 13.78758119, 14.06443504]])

In [8]:
np.subtract(x, y)

array([[-0.69943013,  0.90274368,  1.15670434,  2.79514471,  3.96409963],
       [ 4.77271678,  5.19921464,  6.62296976,  7.56078616,  8.19682224],
       [ 9.05899459, 10.5538166 , 11.41295649, 12.21241881, 13.93556496]])

In [9]:
np.multiply(x, y)

array([[ 0.        ,  0.09725632,  1.68659133,  0.61456588,  0.14360148],
       [ 1.13641609,  4.80471218,  2.63921169,  3.51371068,  7.22859985],
       [ 9.41005406,  4.90801742,  7.0445221 , 10.23855543,  0.90209061]])

In [10]:
np.divide(x, y)

array([[  0.        ,  10.28210865,   2.37164744,  14.64448373,
        111.41946563],
       [ 21.9989845 ,   7.49264444,  18.56614999,  18.21436248,
         11.20548954],
       [ 10.62693151,  24.65353924,  20.44141503,  16.50623481,
        217.27307412]])

In [11]:
x + y

array([[ 0.69943013,  1.09725632,  2.84329566,  3.20485529,  4.03590037],
       [ 5.22728322,  6.80078536,  7.37703024,  8.43921384,  9.80317776],
       [10.94100541, 11.4461834 , 12.58704351, 13.78758119, 14.06443504]])

In [12]:
x - y

array([[-0.69943013,  0.90274368,  1.15670434,  2.79514471,  3.96409963],
       [ 4.77271678,  5.19921464,  6.62296976,  7.56078616,  8.19682224],
       [ 9.05899459, 10.5538166 , 11.41295649, 12.21241881, 13.93556496]])

In [13]:
x * y

array([[ 0.        ,  0.09725632,  1.68659133,  0.61456588,  0.14360148],
       [ 1.13641609,  4.80471218,  2.63921169,  3.51371068,  7.22859985],
       [ 9.41005406,  4.90801742,  7.0445221 , 10.23855543,  0.90209061]])

In [14]:
x / y

array([[  0.        ,  10.28210865,   2.37164744,  14.64448373,
        111.41946563],
       [ 21.9989845 ,   7.49264444,  18.56614999,  18.21436248,
         11.20548954],
       [ 10.62693151,  24.65353924,  20.44141503,  16.50623481,
        217.27307412]])

#### 통계 함수
 - 평균, 분산, 중앙, 최대, 최소값 등등 통계 관련된 함수가 내장

In [15]:
np.mean(y)

0.4902984487029976

In [16]:
np.max(y)

0.9410054058426895

In [17]:
np.argmax(y)

10

In [18]:
np.var(y)

0.0915914476855431

In [19]:
np.median(y)

0.4461834015581545

#### 집계함수
 - 합계(sum), 누적합계(cumsum) 등등 계산 가능

In [20]:
y

array([[0.69943013, 0.09725632, 0.84329566, 0.20485529, 0.03590037],
       [0.22728322, 0.80078536, 0.37703024, 0.43921384, 0.80317776],
       [0.94100541, 0.4461834 , 0.58704351, 0.78758119, 0.06443504]])

In [21]:
np.sum(y)

7.354476730544964

In [22]:
np.cumsum(y)

array([0.69943013, 0.79668644, 1.6399821 , 1.8448374 , 1.88073777,
       2.10802098, 2.90880635, 3.28583659, 3.72505042, 4.52822818,
       5.46923359, 5.91541699, 6.5024605 , 7.29004169, 7.35447673])

#### any, all 함수
 - any: 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
 - all: 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [23]:
z = np.random.randn(10)
print(z)

[ 0.44997953  0.24458036  0.36252761 -0.43048457 -0.64587806 -0.51851122
  0.92365251  0.65601203 -0.27250585  0.37397061]


In [25]:
z > 0

array([ True,  True,  True, False, False, False,  True,  True, False,
        True])

In [26]:
np.any(z > 0)

True

In [27]:
np.all(z > 0)

False

#### where 함수
 - 조건에 따라 선별적으로 값을 선택 가능
 - 사용 예) 음수인경우는 0, 나머지는 그대로 값을 쓰는 경우

In [28]:
z = np.random.rand(10)
print(z)

[0.71282477 0.44244417 0.11987338 0.23230123 0.35804265 0.9900952
 0.07019114 0.94527718 0.80162136 0.10463098]


In [30]:
np.where(z > 0, z, 0)    #R에서 if문이랑 동일한 원리

array([0.71282477, 0.44244417, 0.11987338, 0.23230123, 0.35804265,
       0.9900952 , 0.07019114, 0.94527718, 0.80162136, 0.10463098])