## 학습목표
 1. 브로드캐스팅의 이해

In [1]:
import numpy as np

#### 브로드캐스팅
  - Shape이 같은 두 ndarray에 대한 연산은 각 원소별로 진행
  - 연산되는 두 ndarray가 다른 Shape을 갖는 경우 브로드 캐스팅(Shape을 맞춤) 후 진행
    
    


#### 브로드캐스팅 Rule
 - [공식문서](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#general-broadcasting-rules)
 - 뒷 차원에서 부터 비교하여 Shape이 같거나, 차원 중 값이 1인 것이 존재하면 가능

![브로드캐스팅 예](https://www.tutorialspoint.com/numpy/images/array.jpg)
    - 출처: https://www.tutorialspoint.com/numpy/images/array.jpg 

* Shape이 같은 경우의 연산

In [2]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.81774021 0.35673573 0.23438408 0.53759544 0.06357266]
 [0.3666893  0.17366417 0.3736994  0.49314044 0.13940387]
 [0.23127612 0.08063489 0.84427276 0.32043063 0.64869232]]


In [3]:
x + y

array([[ 0.81774021,  1.35673573,  2.23438408,  3.53759544,  4.06357266],
       [ 5.3666893 ,  6.17366417,  7.3736994 ,  8.49314044,  9.13940387],
       [10.23127612, 11.08063489, 12.84427276, 13.32043063, 14.64869232]])

In [4]:
x * y

array([[ 0.        ,  0.35673573,  0.46876816,  1.61278631,  0.25429063],
       [ 1.8334465 ,  1.04198503,  2.61589578,  3.94512356,  1.25463484],
       [ 2.31276119,  0.88698381, 10.13127309,  4.1655982 ,  9.08169243]])

* Scalar(상수)와의 연산

In [5]:
x + 2

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [6]:
x * 2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [7]:
x ** 2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]], dtype=int32)

In [8]:
x % 2 == 0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

* Shape이 다른 경우 연산

In [14]:
a = np.arange(12).reshape(4, 3)
b = np.arange(100, 103)
c = np.arange(1000, 1004)
d = b.reshape(1, 3)

print(a)
print(b)
print(c)
print(d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[100 101 102]
[1000 1001 1002 1003]
[[100 101 102]]


In [12]:
a + b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [13]:
# 뒷 차원이 다르므로 계산 불가
a + c

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [15]:
a + d

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])